#注意：缩进不要使用Tab，SpringBoot会无法解析报错
spring:
  profiles:
    active: dev # 激活开发环境配置
    
---
server:
  port: 8003
spring:
  profiles: dev
  application:
    name: cloud-flexservice #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
eureka:
  client:
    registerWithEureka: true # 服务注册
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    prefer-ip-address: true #访问路径就会显示成IP地址

feign:
  hystrix:
    enabled: true # 开启服务熔断器
    
---
server:
  port: 8003
spring:
  profiles: runtime
eureka:
  client:
    registerWithEureka: true # 服务注册
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    prefer-ip-address: true #访问路径就会显示成IP地址

feign:
  hystrix:
    enabled: true # 开启服务熔断器